site_name: ID Technical Documentation

# Configuration
site_dir: site
theme:
  name: material
extra_css:
 - 'stylesheets/unibe.css'
use_directory_urls: false

# Copyright footer
copyright: 'Copyright &copy; University of Bern, IT Service Office'
# Social links at botoom right
repo_name: 'id-unibe-ch/id.docs'
repo_url: 'https://github.com/id-unibe-ch/id.docs'
edit_uri: ''

# See https://python-markdown.github.io/extensions/ and
# See https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions#Bundles
#     https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list

nav:
  - Home: index.md